// Copyright 2017-2025 @bitriel/chain-list authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@bitriel/chain-list', path: 'auto', type: 'auto', version: '1.0.2' };
